# Generated by Django 5.2.4 on 2025-07-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
