# Generated by Django 5.2.4 on 2025-07-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_completed_at_task_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
