# Generated by Django 5.2.4 on 2025-07-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_create_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('prompt_response', models.TextField(blank=True, null=True)),
                ('status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
